{{ config(materialized = 'table')}}

WITH patTab AS (
    SELECT
    PATIENT_ID,
    CASE WHEN DEATHDATE IS NULL THEN DATEDIFF('year', BIRTHDATE, START_DATE) ELSE NULL END AS AGE,
    CASE WHEN GENDER = 'F' THEN 1 ELSE 0 END AS FEMALE
    FROM {{ ref('mart_conditions_overview') }}
),

condTab AS (
    SELECT
        YEAR,
        COUNT(DISTINCT PATIENT_ID) AS TOTAL_NUM_PAT,
        COUNT(DISTINCT ENCOUNTER_ID) AS TOTAL_NUM_ENC
    FROM {{ ref('mart_conditions_overview') }}
    GROUP BY YEAR
)

SELECT
    c.COND_DESCRIPTION,
    c.CODE,
    c.ICD10_CODE,
    c.YEAR,
    COUNT(DISTINCT c.PATIENT_ID) AS NUM_PAT,
    MAX(ct.TOTAL_NUM_PAT) AS TOTAL_NUM_PAT,
    COUNT(DISTINCT c.PATIENT_ID) / MAX(ct.TOTAL_NUM_PAT) AS RATE_PAT,
    COUNT(DISTINCT c.ENCOUNTER_ID) AS NUM_ENCOUNTERS,
    MAX(ct.TOTAL_NUM_ENC) AS TOTAL_NUM_ENC,
    COUNT(DISTINCT c.ENCOUNTER_ID) / MAX(ct.TOTAL_NUM_ENC) AS RATE_ENC,
    AVG(p.AGE) AS AVG_AGE,
    AVG(p.FEMALE) AS AVG_FEMALE,
    AVG(c.PRO_COST) AS AVG_COST
FROM {{ ref('mart_conditions_overview') }} c
LEFT JOIN patTab p ON c.PATIENT_ID = p.PATIENT_ID
LEFT JOIN condTab ct ON ct.YEAR = c.YEAR
GROUP BY c.COND_DESCRIPTION, c.CODE, c.ICD10_CODE, c.YEAR