{{ config(materialized = 'view')}}

SELECT
PATIENT AS PATIENT_ID,
ENCOUNTER AS ENCOUNTER_ID,
START_DATE,
STOP_DATE,
DESCRIPTION AS MED_DESCRIPTION,
TRY_CAST(NULLIF(BASE_COST, '') AS FLOAT) AS MED_BASE_COST,
TRY_CAST(NULLIF(PAYER_COVERAGE, '') AS FLOAT) AS MED_PAYER_COVERAGE,
TRY_CAST(NULLIF(DISPENSES, '') AS INTEGER) AS DISPENSES,
TRY_CAST(NULLIF(TOTALCOST, '') AS FLOAT) AS MED_TOTAL_COST,
REASONDESCRIPTION AS MED_REASON
FROM {{ source('synthea_raw', 'medications')}} 
