{{ config(materialized = 'view')}}

SELECT
    ID AS PATIENT_ID,
    BIRTHDATE,
    DEATHDATE,
    GENDER,
    RACE,
    ETHNICITY,
    FIRST AS FIRST_NAME,
    LAST AS LAST_NAME,
    STATE,
    COUNTY,
    TRY_CAST(NULLIF(HEALTHCARE_EXPENSES, '') AS FLOAT) AS HEALTHCARE_EXPENSES,
    TRY_CAST(NULLIF(HEALTHCARE_COVERAGE, '') AS FLOAT) AS HEALTHCARE_COVERAGE
FROM {{ source('synthea_raw', 'patients')}} 