{{ config(materialized = 'view')}}

SELECT
ID AS ENCOUNTER_ID,
START_DATE,
STOP_DATE,
PATIENT AS PATIENT_ID,
ORGANIZATION AS ORG_ID,
ENCOUNTERCLASS AS ENCOUNTER_CLASS,
DESCRIPTION AS ENC_DESCRIPTION,
TRY_CAST(NULLIF(BASE_ENCOUNTER_COST, '') AS FLOAT) AS ENC_BASE_COST,
TRY_CAST(NULLIF(TOTAL_CLAIM_COST, '') AS FLOAT) AS ENC_TOTAL_CLAIM_CAST,
TRY_CAST(NULLIF(PAYER_COVERAGE, '') AS FLOAT) AS ENC_PAYER_COVERAGE,
REASONDESCRIPTION AS ENC_REASON
FROM {{ source('synthea_raw', 'encounters')}} 